# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-PSR
version:      0.30
version_from: 
installdirs:  site
requires:
    Config::Tiny:                  0
    File::Spec:                    0
    Net::AIM:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
